"""Add email field to transactions table

Revision ID: b0c06c4f338c
Revises: a5e268a123ad
Create Date: 2025-12-06 14:31:20.997490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c06c4f338c'
down_revision: Union[str, Sequence[str], None] = 'a5e268a123ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('transactions', 'authorization_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'authorization_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('transactions', 'email')
    # ### end Alembic commands ###
