"""initial migrations

Revision ID: d2f873264907
Revises: 7e6df606d708
Create Date: 2025-12-11 08:16:48.892317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f873264907'
down_revision: Union[str, Sequence[str], None] = '7e6df606d708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_key', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_key_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_number', sa.String(length=13), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_wallet_number', 'wallets', ['wallet_number'], unique=False)
    op.create_index('idx_wallet_user_id', 'wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallets_wallet_number'), 'wallets', ['wallet_number'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='transactionstatus'), nullable=False),
    sa.Column('transaction_type', sa.Enum('deposit', 'transfer', name='transactiontype'), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('sender_wallet_id', sa.UUID(), nullable=True),
    sa.Column('recipient_wallet_id', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_reference', 'transactions', ['reference'], unique=False)
    op.create_index('idx_transaction_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transaction_type', 'transactions', ['transaction_type'], unique=False)
    op.create_index('idx_transaction_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index('idx_transaction_user_id', table_name='transactions')
    op.drop_index('idx_transaction_type', table_name='transactions')
    op.drop_index('idx_transaction_status', table_name='transactions')
    op.drop_index('idx_transaction_reference', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_wallet_number'), table_name='wallets')
    op.drop_index('idx_wallet_user_id', table_name='wallets')
    op.drop_index('idx_wallet_number', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_api_key_user_active', table_name='api_keys')
    op.drop_index('idx_api_key_key', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
